language: c

before_install:
   - sudo apt-get update -qq > /dev/null
   - sudo apt-get install -qq mono-devel mono-gmcs gtk-sharp2 > /dev/null
 
script:
  - cd RevertScreenResolution/
  - xbuild RevertScreenResolution.sln
